FROM alpine
RUN apk add --update --no-cache alpine-sdk bash python
WORKDIR /root
RUN git clone https://github.com/edenhill/librdkafka.git
WORKDIR /root/librdkafka
RUN /root/librdkafka/configure
RUN make
RUN make install
#For golang applications
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2


# Make info file about this build
RUN apk update && apk upgrade && \
  mkdir -p /etc/BUILDS/ && \
  printf "Build of nimmis/alpine-golang:1.7, date: %s\n"  `date -u +"%Y-%m-%dT%H:%M:%SZ"` > /etc/BUILDS/alpine-golang && \

# add extra package for installation
apk add curl && \

# download and upack golang
curl https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz | tar xzf - -C / && \
mv /go /goroot && \

# remove extra packages
apk del curl && \

# remove cached info
rm -rf /var/cache/apk/*

ENV GOROOT=/goroot \
    GOPATH=/gopath \
    GOBIN=/gopath/bin \
    PATH=${PATH}:/goroot/bin:/gopath/bin
